aws:
  access-key: AKIA4XGGFKSZAEG2CUZR
  secret-key: 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
  region: us-east-1
  cognito:
    user-pool-id: us-east-1_nOCYaX80Q
    app-client-id: barqb611paspe2qnd89jbmk1u
    app-client-secret: 1122r4et2sneumc3vgir9l5l7oog3s5fi604ksmt06g6v2njko4j
